name: Test

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
   my_test:
     runs-on: ubuntu-latest
     name: Unit tests
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Setup BATS
         uses: mig4/setup-bats@v1
         with:
           bats-version: 1.6.0
       - name: Setup Bats libs
         uses: brokenpip3/setup-bats-libs@0.1.0
       - name: Run tests
         run: bats tests/logger.bats
         env:
           BATS_EXTRA_LIB_PATH: /usr/lib
